language: python
os: "linux"
python:
  # - "3.4"
  # - "3.5"
  - "3.6"
  - "3.7.3"
# Setup anaconda, see https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
# Install packages
env:
  - CODECOV_TOKEN=2aa5e8a7-cab1-4412-be59-a874a5a4b45b
install:
  - sed -i "s/defaults::python.*/defaults::python=$TRAVIS_PYTHON_VERSION/" environment.yml
  - conda env create -n env_name --file environment.yml
  - source activate env_name
  - conda install -y -c conda-forge -- pytest-cov codecov;
  - conda install -c bioconda -c conda-forge -y stringtie scallop gmap star hisat2 prodigal blast diamond transdecoder conda-forge::gnuplot kallisto samtools gffread
  - python setup.py develop;
script:
  - pytest -m slow Mikado/tests/test_system_calls.py::SerialiseChecker::test_subprocess_multi_empty_orfs
  - pytest --cov Mikado --cov-config=.coveragerc -m '(slow or not slow) and not triage';
  - cd sample_data; snakemake --jobs 5 --cores 5
  - cd ..;
  - python -c "import Mikado; Mikado.test(label='fast')";
  # Check that the seed is set properly
  - mikado pick --log $(pwd)/pick.20a.log --procs 2 --seed 20 --fasta Mikado/tests/chr5.fas.gz  --json-conf Mikado/tests/check_seed.yaml -od 20a Mikado/tests/check_seed.gtf
  - mikado pick --log $(pwd)/pick.20b.log --procs 2 --seed 20 --fasta Mikado/tests/chr5.fas.gz  --json-conf Mikado/tests/check_seed.yaml -od 20b Mikado/tests/check_seed.gtf  
  - mikado pick --log $(pwd)/pick.20c.log --procs 2 --seed 20 --fasta Mikado/tests/chr5.fas.gz  --json-conf Mikado/tests/check_seed.yaml -od 20c Mikado/tests/check_seed.gtf
  - mikado pick --log $(pwd)/pick.20d.log --procs 2 --seed 20 --fasta Mikado/tests/chr5.fas.gz  --json-conf Mikado/tests/check_seed.yaml -od 20d Mikado/tests/check_seed.gtf     
  - mikado pick --log $(pwd)/pick.10.log --procs 2 --seed 1000 --fasta Mikado/tests/chr5.fas.gz  --json-conf Mikado/tests/check_seed.yaml -od 1000 Mikado/tests/check_seed.gtf
  - if [[ $(diff -q 20a 20b) || $(diff -q 20a 20c) || $(diff -q 20a 20d) ]]; then exit 1; fi
  - if [[ ! $(diff -q 20a 1000) ]]; then exit 1; fi

after_success:
  - codecov 
