FROM ubuntu:bionic
WORKDIR /
RUN apt update -y && apt upgrade -y
RUN apt install -y build-essential git wget tar zlib1g-dev make gcc
WORKDIR /usr/local/src
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/conda
ENV PATH="/usr/local/conda/bin:$PATH"
RUN . /usr/local/conda/bin/activate
RUN conda update -n base -c defaults conda
RUN ln -s /usr/local/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
RUN conda install -y -c conda-forge pip python==3.6.7
RUN git clone https://github.com/EI-CoreBioinformatics/mikado.git
WORKDIR /usr/local/src/mikado
RUN sed -i 's/;.*//' requirements.txt
RUN conda install --update-all -y -c conda-forge -c bioconda -c anaconda --file requirements.txt
RUN python setup.py bdist_wheel
RUN pip install dist/*whl
RUN echo -e "#!/bin/bash\ncd /usr/local/src/mikado;\ngit log | head -n1 | cut -f 2 -d ' '''" > /usr/local/bin/show_commit_hash && chmod 775 /usr/local/bin/show_commit_hash
RUN conda install -y -c bioconda -c anaconda -c conda-forge samtools==1.9 openssl=1.0 prodigal blast diamond==0.9.24 transdecoder==5.5.0
CMD mikado