package:
  name: mikado
  version: "1.0.0beta10"

source:
  git_rev: "1.0.0b9"
  git_url: "https://github.com/lucventurini/mikado.git"

requirements:
  build:
    - python
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - biopython
    - nose
    - scikit-learn
    - scipy
    # - drmaa
    - snakemake
    - docutils
    - tabulate
    - ujson
  run:
    - python
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - biopython
    - nose
    - scikit-learn
    - scipy
    # - drmaa
    - snakemake
    - docutils
    - tabulate
    - ujson

test:
  requires:
    - nose
  commands:
    - python setup.py nosetests

about:
  home: https://mikado.readthedocs.io/
  license: GPL3
  license_file: LICENSE.txt