package:
  name: mikado
  version: "1.1"

source:
  fn: Mikado-1.1.tar.gz
  md5: 76ed8a799a078d2cd2bc36c45d3b3e4d
  url: https://pypi.python.org/packages/c2/b9/41d0a6f2ebad5eab5bc183beca8de854b4187266c6674ae6da0d86053f63/Mikado-1.1.tar.gz#md5=76ed8a799a078d2cd2bc36c45d3b3e4d

requirements:
  build:
    - python
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - biopython
    - nose
    - scikit-learn
    - scipy
    # - drmaa
    - snakemake
    - docutils
    - tabulate
    - ujson
  run:
    - python
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - biopython
    - nose
    - scikit-learn
    - scipy
    # - drmaa
    - snakemake
    - docutils
    - tabulate
    - ujson

test:
  requires:
    - nose
  commands:
    - python setup.py nosetests

about:
  home: https://mikado.readthedocs.io/
  license: GPL3
  license_file: LICENSE.txt