{% set name = "mikado" %}
{% set version = "1.1" %}
{% set md5 = "76ed8a799a078d2cd2bc36c45d3b3e4d" %}
{% set sha = "aca1a822799de45494b56a0a2bf66e7eac49eb25cde6642f5da7aeb6515e573e" %}


package:
  name: {{name}}
  version: {{version}}

source:
  fn: Mikado-{{version}}.tar.gz
  sha256: {{ sha }}
  md5: {{ md5 }}
  url: https://pypi.python.org/packages/c2/b9/41d0a6f2ebad5eab5bc183beca8de854b4187266c6674ae6da0d86053f63/Mikado-1.1.tar.gz

about:
  home: https://github.com/EI-CoreBioinformatics/mikado/
  summary: "Mikado is a lightweight Python3 pipeline whose purpose is to facilitate the identification of expressed loci from RNA-Seq data and to select the best models in each locus."
  license: GPL3
  license_file: LICENSE.txt

build:
  number: 0
  skip: True # [osx or py27]

requirements:
  build:
    - llvm # [osx]
    - libgcc # [not osx]
    - gcc
    - python
    - zlib 
    - sqlite
    - blast
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - biopython
    - nose
    - scikit-learn
    - scipy
    - snakemake
    - docutils
    - tabulate
    - intervaltree
    - sqlalchemy-utils
    - pyfaidx
    - python-magic
    - samtools
    - pysam
    - ujson
  run:
    - python
    - libgcc # [not osx]
    - setuptools
    - wheel
    - pyyaml
    - jsonschema
    - cython
    - numpy
    - networkx
    - sqlalchemy
    - sqlalchemy-utils
    - biopython
    - nose
    - scikit-learn
    - scipy
    - drmaa
    - python-drmaa
    - prodigal
    - snakemake
    - docutils
    - tabulate
    - intervaltree
    - pyfaidx
    - samtools
    - pysam
    - python-magic
    # - portcullis
    - ujson

test:
  requires:
    - nose
  commands:
    - python setup.py nosetests

about:
  home: https://mikado.readthedocs.io/
  license: GPL3
  license_file: LICENSE.txt