{% set name = "mikado" %}
{% set version = "1.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ version }}.{{ file_ext }}'
  url: https://github.com/lucventurini/mikado/archive/1.5.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True # [py27 or osx or py33 or py34]
  number: 0
  entry_points:
    - mikado = Mikado:main
    - daijin = Mikado.daijin:main
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - wheel >=0.28.0
    - pyyaml
    - jsonschema
    - cython >=0.28.2
    - numpy >=1.16
    - networkx >=1.10
    - sqlalchemy >=1
    - sqlalchemy-utils
    - biopython >=1.70
    - intervaltree
    - nose
    - pyfaidx
    - scikit-learn >=0.20
    - scipy >=0.15.0
    - libmagic
    - python-magic
    - drmaa
    - snakemake
    - docutils !=0.13.1
    - tabulate
    - ujson
    - typing
    - pytest-cov
  run:
    - python
    - wheel >=0.28.0
    - pyyaml
    - jsonschema
    - cython >=0.28.2
    - numpy
    - networkx >=1.10
    - sqlalchemy >=1
    - sqlalchemy-utils
    - biopython >=1.70
    - intervaltree
    - pyfaidx
    - scikit-learn >=0.20
    - scipy >=0.15.0
    - libmagic
    - python-magic
    - drmaa
    - snakemake
    - docutils !=0.13.1
    - tabulate
    - ujson
    - portcullis
    - typing
    - pandas
    - pytest-cov

test:
  imports:
    - Mikado
    - Mikado.configuration
    - Mikado.daijin
    - Mikado.loci
    - Mikado.parsers
    - Mikado.picking
    - Mikado.preparation
    - Mikado.scales
    - Mikado.serializers
    - Mikado.serializers.blast_serializer
    - Mikado.subprograms
    - Mikado.subprograms.util
    - Mikado.tests
    - Mikado.transcripts
    - Mikado.transcripts.transcript_methods
    - Mikado.utilities
  commands:
    - mikado --help
    - daijin --help
    - python -c "import Mikado; Mikado.test()"

about:
  home: https://github.com/EI-CoreBioinformatics/mikado/
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  license_family: LGPL
  summary: A Python3 annotation program to select the best gene model in each locus

