blast:
  database: uniprot_sprot_plants.fasta
  evalue: 0.00001
  execute: true
  max_target_seqs: 3
  num_threads: 4
  program: blastx
chimera_split:
  blast_check: true
  execute: true
  blast_params:
    leniency: STRINGENT
log_settings:
  log_level: DEBUG
source: "Mikado"
alternative_splicing:
  report: true
  max_isoforms: 3
orf_loading:
  strand_specific: true
run_options:
  purge: true
  remove_overlapping_fragments: true
  fragments_maximal_cds: 100
  subloci_from_cds_only: true
  threads: 5
  preload: true
scoring_file: plants.yaml