db_settings:
  #  Settings related to DB connection. Parameters:
  #  db: the DB to connect to. Required. Default: mikado.db
  #  dbtype: Type of DB to use. Choices: sqlite, postgresql, mysql. Default: sqlite.
  #  dbhost: Host of the database. Unused if dbtype is sqlite. Default: localhost
  #  dbuser: DB user. Default: 
  #  dbpasswd: DB password for the user. Default: 
  #  dbport: Integer. It indicates the default port for the DB.
  db: mikado.db  # ara_test  #
  dbhost: localhost
  dbpasswd: ''
  dbport: 0
  dbtype: sqlite  # mysql  #
  dbuser: venturil
filename: /usr/users/ga002/venturil/workspace/Mikado/mikado_lib.json
log_settings:
  #  Settings related to the logs. Keys:
  #  log: the name of the log file. Default: mikado.log
  #  log_level: verbosity. In decreasing order: DEBUG, INFO, WARNING,
  #  ERROR, CRITICAL
  log: mikado.log
  log_level: INFO
pick:
  chimera_split:
    #  Parameters related to the splitting of transcripts in the presence of
    #  two or more ORFs. Parameters:
    #  - execute: whether to split multi-ORF transcripts at all. Boolean.
    #  - blast_check: whether to use BLAST information to take a decision. See blast_params
    #  for details.
    #  - blast_params: Parameters related to which BLAST data we want to analyse.
    blast_check: true
    blast_params:
      #  Parameters for the BLAST check prior to splitting.
      #  - evalue: Minimum evalue for the whole hit. Default: 1e-6
      #  - hsp_evalue: Minimum evalue for any HSP hit (some might be discarded even
      #  if the whole hit is valid). Default: 1e-6
      #  - leniency: One of STRINGENT, LENIENT, PERMISSIVE. Default: LENIENT
      #  - max_target_seqs: maximum number of hits to consider. Default: 3
      #  - minimal_hsp_overlap: minimum overlap of the ORF with the HSP (*not* reciprocal).
      #  Default: 0.8, i.e. 80%
      #  - min_overlap_duplication: minimum overlap (in %) for two ORFs to consider
      #  them as target duplications.
      #    This means that if two ORFs have no HSPs in common, but the coverage of
      #  their disjoint HSPs covers more
      #    Than this % of the length of the *target*, they represent most probably
      #  a duplicated gene.
      leniency: PERMISSIVE
      min_overlap_duplication: 0.8
    execute: true
  files:
    #  Input and output files for Mikado pick.
    #  - input: input GTF/GFF3 file. Default: mikado_prepared.gtf
    #  - loci_out: output GFF3 file from Mikado pick. Default: mikado.loci.gff3
    #  - subloci_out: optional GFF file with the intermediate subloci. Default: no
    #  output
    #  - monoloci_out: optional GFF file with the intermediate monoloci. Default:
    #  no output
    input: mikado_prepared.gtf
    loci_out: mikado.loci.gff3
    monoloci_out: ''
    subloci_out: ''
  orf_loading:
    #  Parameters related to ORF loading.
    #  - minimal_secondary_orf_length: Minimum length of a *secondary* ORF
    #    to be loaded after the first, in bp. Default: 200 bps
    #  - minimal_orf_length: Minimum length in bps of an ORF to be loaded,
    #    as the primary ORF, onto a transcript. Default: 50 bps
    #  - strand_specific: Boolean flag. If set to true, monoexonic transcripts
    #    will not have their ORF reversed even if they would have an ORF on the opposite
    #  strand.
    minimal_orf_length: 50
    minimal_secondary_orf_length: 200
    strand_specific: true
  output_format:
    #  Parameters related to the output format.
    #    - source: prefix for the source field in the mikado output.
    #    - id_prefix: prefix for the ID of the genes/transcripts in the output
    id_prefix: mikado
    source: Mikado
  run_options:
    #  Generic run options.
    #  - shm: boolean flag. If set and the DB is sqlite, it will be copied onto the
    #  /dev/shm faux partition
    #  - shm_db: String. It indicates a DB that has to be copied onto SHM and left
    #  there for
    #    concurrent Mikado runs.
    #  - shm_shared: boolean flag. If set, the database loaded onto SHM will be shared
    #  and should not be
    #    deleted at the end of the run (see shm_db).
    #    for faster access. Default: false
    #  - exclude_cds: boolean flag. If set, the CDS information will not be printed
    #  in Mikado output. Default: false
    #  - purge: boolean flag. If set, all loci where all transcripts have a score
    #  of 0 will be excluded
    #    from the output. Default: false
    #  - remove_overlapping_fragments: boolean flag. If set, fragments (defined as
    #  monoexonic loci
    #    classified as P,x,i or p compared to another locus, will be removed from
    #  the output.
    #  - fragments_maximal_cds: a monoexonic superlocus will never be considered a
    #  fragment if its longest CDS is over
    #    this length. Default: 100 bps.
    #  - threads: number of threads to use. Default: 1
    #  - preload: boolean flag. If set, the whole database will be preloaded into
    #  memory for faster access. Useful when
    #    using SQLite databases.
    exclude_cds: false
    fragments_maximal_cds: 100
    preload: false
    purge: false
    remove_overlapping_fragments: true
    shm: false
    shm_db: ''
    subloci_from_cds_only: false
    threads: 5
  scoring_file: plants.yaml
soft_requirements:
  intron_range:
  - 0
  - 9223372036854775807
