# Read parameters
r1: ["SP_R1.5m.fq"]
r2: ["SP_R2.5m.fq"]
strandedness: ["fr-firststrand"]

# Array of names to assign each sample
samples: ["5m"]

# Species name
name: "spombe"

# Alignment parameters
min_intron: "20"
max_intron: "10000"

# Reference
reference:
        # Required.  Fasta format genome
        genome: "Spombe.genome.fa"

        # Optional.  GTF format transcriptome
        transcriptome: ""


# Run options
#
# output directory
out_dir: "spombe_slurm"
# Threads per process
threads: "4"
# Trinity max memory
tgg_max_mem: "20G"
# Scheduler: LSF,PBS,SLURM, none
scheduler: "SLURM"

# Alignment methods to use. Supported tools: "tophat", "gsnap", "star", "hisat"
align_methods:
        tophat: ["", "--microexon-search"]
        star: ["","--alignSJoverhangMin 12"]
        hisat: [""]

# Assembly_methods to use:  Supported tools: "cufflinks", "stringtie", "class", "trinity"
asm_methods:
        stringtie: [""]
        class: [""]


# Choose program version
load:
        tophat: "set +u && source tophat-2.1.0_lv && set -u"
        gmap: "set +u && source gmap-20150929 && set -u"
        star: "set +u && source star-2.4.2a && set -u"
        hisat: "set +u && source HISAT-2.0.4 && set -u"
        samtools: "set +u && source samtools-1.2 && set -u"
        cufflinks: "set +u && source cufflinks-2.2.1_gk && set -u"
        trinity: "set +u && source trinityrnaseq-2.0.6 && set -u"
        stringtie: "set +u && source stringtie-1.0.4 && set -u"
        class: "set +u && source class-2.12 && set -u"
        transdecoder: "set +u && source transdecoder-3.0.0 && set -u"
        portcullis: "set +u && source portcullis-0.17.0 && set -u"
        mikado: "set +u && source mikado-0.24.0 && set -u"
        blast: "set +u && source blast-2.2.31 && set -u"

# Extra options for programs
aln_index:
        star_index: "--genomeSAindexNbases 11"

portcullis:
        do: True
        # In portcullis, whether or not to keep junctions based on their splice site status.  
        # Valid options: OFF,C,S,N. 
        # Where C = Canonical junctions (GU-AG), S = Semi-canonical junctions (AT-AC, or  GT-AG), 
        # N = Non-canonical.  OFF means, keep all junctions (i.e. don't filter by canonical status).  
        # User can separate options by a comma to keep two categories.
        #
        canonical_juncs: "C,S"
        
transdecoder:
        min_protein_len: 100


# If not empty then run BLASTX using transcripts against this protein database                
blastx:
        prot_db: "uniprot_sprot_fungi.fasta"
        evalue: "0.000000001"
        max_target_seqs: "10"
        chunks: 10

mikado:
        # Can run multiple mikado modes in parallel.  Available mikado modes: {"nosplit,"split","stringent","lenient","permissive"}
        modes: ["nosplit"]



# Mikado configuration
# ##################
#
# Database
db_settings:
        #  Settings related to DB connection. Parameters:
        #  db: the DB to connect to. Required. Default: mikado.db
        #  dbtype: Type of DB to use. Choices: sqlite, postgresql, mysql. Default: sqlite.
        #  dbhost: Host of the database. Unused if dbtype is sqlite. Default: localhost
        #  dbuser: DB user. Default: 
        #  dbpasswd: DB password for the user. Default: 
        #  dbport: Integer. It indicates the default port for the DB.
        db: mikado.db
        dbtype: sqlite

#Mikado picking
pick:
        # Available scoring models: {mammalian.yaml,plant.yaml}
        scoring: "plant.yaml"
        alternative_splicing:
                #  Parameters related to alternative splicing reporting.
                #  - report: whether to report at all or not the AS events.
                #  - min_cds_overlap: minimum overlap between the CDS of the primary transcript
                #  and any AS event. Default: 60%.
                #  - max_isoforms: Maximum number of isoforms per locus. 1 implies no AS reported.
                #  Default: 3
                max_isoforms: 3
                report: true
                chimera_split:
                        #  Parameters related to the splitting of transcripts in the presence of
                        #  two or more ORFs. Parameters:
                        #  - execute: whether to split multi-ORF transcripts at all. Boolean.
                        #  - blast_check: whether to use BLAST information to take a decision. See blast_params
                        #  for details.
                        #  - blast_params: Parameters related to which BLAST data we want to analyse.
                        blast_check: true
                        blast_params:
                                #  Parameters for the BLAST check prior to splitting.
                                #  - evalue: Minimum evalue for the whole hit. Default: 1e-6
                                #  - leniency: One of STRINGENT, LENIENT, PERMISSIVE. Default: LENIENT
                                #  - max_target_seqs: maximum number of hits to consider. Default: 3
                                leniency: LENIENT
                                min_overlap_duplication: 0.8
                        execute: true

# Mikado serialise
serialise:
        #  Options related to serialisation
        #  - force: whether to drop and reload everything into the DB
        force: true

