# Read parameters
r1: ["spombe.III.R1.fastq.gz"]
r2: ["spombe.III.R2.fastq.gz"]
strandedness: ["fr-unstranded"]  # ["fr-firststrand"]

# Array of names to assign each sample
samples: ["5m"]

# Species name
name: "spombe"

# Alignment parameters
min_intron: "20"
max_intron: "10000"

# Reference genome
ref: "spombe.III.fasta"

# Run options
#
# output directory
out_dir: "local_spombe"
# Threads per process
threads: "4"
# Trinity max memory
tgg_max_mem: "20G"
# Scheduler: LSF,PBS,SLURM
scheduler: ""

# Methods to use
#align_methods: ["tophat","gsnap","star", "hisat"]
align_methods: ["hisat"]
#asm_methods: ["cufflinks","stringtie","trinity"]
asm_methods: ["stringtie","class"]

# Choose program version
load:
        tophat: "echo" # "set +u && source tophat-2.1.0_lv && set -u"
        gmap: "echo"  # "set +u && source gmap-20150929 && set -u"
        star: "echo"  # "set +u && source star-2.4.2a && set -u"
        hisat: "echo"  # "set +u && source HISAT-2.0.4 && set -u"
        samtools: "echo"  # "set +u && source samtools-1.2 && set -u"
        cufflinks: "echo"  # "set +u && source cufflinks-2.2.1_gk && set -u"
        trinity: "echo"  # "set +u && source trinityrnaseq-2.0.6 && set -u"
        stringtie: "echo"  # "set +u && source stringtie-1.0.4 && set -u"
        class: "echo"  # "set +u && source class-2.12 && set -u"
        transdecoder: "echo"  # "set +u && source transdecoder-2.0.1 && set -u"
        portcullis: "echo"  # "set +u && source portcullis-0.17.0 && set -u"
        mikado: "echo"  # "set +u && source mikado-0.24.0 && set -u"
        blast: "echo"  # "set +u && source blast-2.2.31 && set -u"

# Extra options for programs
extra:
        star_index: "--genomeSAindexNbases 11"
        tophat: ""
        gsnap: ""
        star: ""
        hisat: ""
        cufflinks: ""
        trinity: "--jaccard_clip"
        stringtie: ""
        class: ""

portcullis:
        do: True
        # In portcullis, whether or not to keep junctions based on their splice site status.  
        # Valid options: OFF,C,S,N. 
        # Where C = Canonical junctions (GU-AG), S = Semi-canonical junctions (AT-AC, or  GT-AG), 
        # N = Non-canonical.  OFF means, keep all junctions (i.e. don't filter by canonical status).  
        # User can separate options by a comma to keep two categories.
        #
        canonical_juncs: "C,S"
        

# If not empty then run BLASTX using transcripts against this protein database                
blastx:
        prot_db: ["uniprot_sprot_fungi.fasta"]
        evalue: "1e-10"
        max_target_seqs: "3"


mikado_mode: "permissive"
mikado_scoring: "plants.yaml"

# Mikado configuration
# ##################
#
# Database
db_settings:
        #  Settings related to DB connection. Parameters:
        #  db: the DB to connect to. Required. Default: mikado.db
        #  dbtype: Type of DB to use. Choices: sqlite, postgresql, mysql. Default: sqlite.
        #  dbhost: Host of the database. Unused if dbtype is sqlite. Default: localhost
        #  dbuser: DB user. Default: 
        #  dbpasswd: DB password for the user. Default: 
        #  dbport: Integer. It indicates the default port for the DB.
        db: mikado.db
        dbtype: sqlite

#Mikado picking
pick:
        alternative_splicing:
                #  Parameters related to alternative splicing reporting.
                #  - report: whether to report at all or not the AS events.
                #  - min_cds_overlap: minimum overlap between the CDS of the primary transcript
                #  and any AS event. Default: 60%.
                #  - max_isoforms: Maximum number of isoforms per locus. 1 implies no AS reported.
                #  Default: 3
                max_isoforms: 3
                report: true
                chimera_split:
                        #  Parameters related to the splitting of transcripts in the presence of
                        #  two or more ORFs. Parameters:
                        #  - execute: whether to split multi-ORF transcripts at all. Boolean.
                        #  - blast_check: whether to use BLAST information to take a decision. See blast_params
                        #  for details.
                        #  - blast_params: Parameters related to which BLAST data we want to analyse.
                        blast_check: true
                        blast_params:
                                #  Parameters for the BLAST check prior to splitting.
                                #  - evalue: Minimum evalue for the whole hit. Default: 1e-6
                                #  - leniency: One of STRINGENT, LENIENT, PERMISSIVE. Default: LENIENT
                                #  - max_target_seqs: maximum number of hits to consider. Default: 3
                                leniency: LENIENT
                                min_overlap_duplication: 0.8
                        execute: true

# Mikado serialise
serialise:
        #  Options related to serialisation
        #  - force: whether to drop and reload everything into the DB
        force: true

