name: Upload to PyPI and TestPyPI
on:
  release:
    types: [published]
jobs:
  build-and-publish:
    name: Build the Mikado release and publish to TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Mikado
        run: >-
          python -m pip install build --user
      - name: Build sdist
        run: >-
          python -m build --sdist --wheel --outdir dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
